export const VERIFY_EMAIL_OR_PHONE = "VERIFY_EMAIL_OR_PHONE";
export const VERIFY_PIN = "VERIFY_PIN";

export const REQUEST = "_REQUEST";
export const SUCCESS = "_SUCCESS";
export const FAILURE = "_FAILURE";

export const SET_TIMER = "SET_TIMER";
export const DECREASE_TIME_BY_ONE_SEC = "DECREASE_TIME_BY_ONE_SEC";
export const RESET_VERIFICATION_STATUS = "RESET_VERIFICATION_STATUS";

export const UPDATE_ERROR = "UPDATE_ERROR";
export const RESET_ERROR = "RESET_ERROR";

export const UPDATE_STORE_FROM_COOKIES = "UPDATE_STORE_FROM_COOKIES";
export const UPDATE_STORE = "UPDATE_STORE";

export const UPDATE_FILES_UPLOAD_ERRORS = "UPDATE_FILES_UPLOAD_ERRORS";
export const ADD_UPLOADED_FILE = "ADD_UPLOADED_FILE";
export const ADD_UPLOADED_FILE_ERROR = "ADD_UPLOADED_FILE_ERROR";
